import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import NavbarSimple from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import Content from '@/components/Content'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col w-full h-screen justify-center items-center bg-gray-500'>
        {children}
      </body >
    </html >
  )
}
